name: model-wine-quality
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Train my model'
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |

          # Your ML workflow goes here
          pip3 install -r requirements.txt
          python3 train.py
          
          echo "Model Metrics"
          cat metrics.txt
          
          echo "## model matrics" -> report.md
          cat metrics.txt >> report.md
